- name: Create resources and setup demo
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    repo_url: "https://github.com/ansible-middleware/wildfly-cluster-demo.git"
    branch: main
    hosts_group_name: demo
    
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ playbook_dir }}/wildfly-cluster-demo"
        version: "{{ branch }}"
        clone: yes
        force: yes

    - name: Create demo resources on opnestack and kubevirt.
      ansible.builtin.import_playbook: create-resources.yml
    
    - meta: refresh_inventory
    - pause:
        minutes: 1

  - name: Run wildfly-cluster-demo
    include_tasks: wildfly-cluster-demo/playbook.yml